controllers/SiteController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\Response;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\AccesoForm;
use app\models\ContactForm;
use app\models\ValidaForma;
use app\models\ValidaFormaAjax;
use app\models\SetearPassword;
use app\models\Usuarios;
use yii\widgets\ActiveForm;
use app\models\FormAlumnos;
use app\models\Alumnos;
use app\models\Grados;
use app\models\AlumnoSearch;
use yii\helpers\Html;
use yii\data\Pagination;
use yii\helpers\Url;
use yii\web\Session;

class SiteController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function actionPanel(){
        $session = Yii::$app->session;
        $user_id = $session->get('userid');
        $usu = Usuarios::findOne($user_id);
        $nombre = null;
        $data = null;
        switch($usu->id_perfil){
            case 1:
                $data = \app\models\Profesor::findOne($usu->id_actor);
            break;
            case 2:
                $data = Alumnos::findOne($usu->id_actor);
            break;
            case 3:
                $data = \app\models\Acudientes::findOne($usu->id_actor);
            break;
        }
        if($data){
            $nombre = $data->primer_nombre." ".$data->segundo_nombre." ".$data->primer_apellido." ".$data->segundo_apellido;
        }
        return $this->render("panel",["userid"=>$user_id,"perfil"=>$usu->id_perfil,"nombre"=>$nombre]);
    }
    public function actiondeletealumno(){
        if(Yii::$app->request->post()){
            $id_alumno = Html::encode($_POST['id_alumno']);
            if((int) $id_alumno){
                if(Alumnos::deleteAll("id_alumno=:id_alumno",[":id_alumno"=>$id_alumno])){
                    echo "Alumno Eliminado Exitosamente";
                    echo "<meta http-equiv='refresh' content='3; ".Url::toRoute("site/viewalumno")."'>";
                }else{
                    echo "Ha ocurrido un error al eliminar el alumno, redireccionando ...";
                    echo "<meta http-equiv='refresh' content='3; ".Url::toRoute("site/viewalumno")."'>";                     
                }
            }else{
                echo "Ha ocurrido un error al eliminar el alumno, redireccionando ...";
                echo "<meta http-equiv='refresh' content='3; ".Url::toRoute("site/viewalumno")."'>";                
            }
        }else{
            return $this->redirect("site/viewalumno");
        }
        //return $this->render("deleteAlumno");
    }
    public function actionViewalumno(){
        /*$table  = new Alumnos;
        $model  = $table->find()->all();
        $form   = new AlumnoSearch;
        $search = null;
        if($form->load(Yii::$app->request->get())){
            if($form->validate()){
                $search = Html::encode($form->q);
                $query = "Select * from alumnos where tipo_documento ilike '%$search%' OR ";
                $query .= " numero_documento ilike '%$search%' OR ";
                $query .= " primer_nombre ilike '%$search%' OR";
                $query .= " segundo_nombre ilike '%$search%' OR";
                $query .= " primer_apellido ilike '%$search%' OR";
                $query .= " segundo_apellido ilike '%$search%'";
                $model = $table->findBySql($query)->all();
            }else{
                $form->getErrors();
            }
        }*/
        $form = new AlumnoSearch;
        $search = null;
        if($form->load(Yii::$app->request->get())){
            if($form->validate()){
                $search  = Html::encode($form->q);
                $table = Alumnos::find()->where(["ilike","tipo_documento",$search])
                        ->orWhere(["ilike","numero_documento",$search])
                        ->orWhere(["ilike","primer_nombre",$search])
                        ->orWhere(["ilike","segundo_nombre",$search])
                        ->orWhere(["ilike","primer_apellido",$search])
                        ->orWhere(["ilike","segundo_apellido",$search]);
                $count = clone $table;
                $pages = new Pagination([
                    "pageSize"=>1,
                    "totalCount" => $count->count()
                ]);
                $model = $table
                        ->offset($pages->offset)
                        ->limit($pages->limit)
                        ->all();
            }else{
                $form->getErrors();
            }
        }else{
            $table = Alumnos::find();
            $count = clone $table;
            $pages = new Pagination([
                "pageSize"=>1,
                "totalCount" => $count->count()
            ]);
            $model = $table
                    ->offset($pages->offset)
                    ->limit($pages->limit)
                    ->all();
        }
        return $this->render("viewalumno",["model"=>$model,"form"=>$form,"search"=>$search,"pages"=>$pages]);
    }
    public function actionCreatealumno(){
        $model = new FormAlumnos;
        $msg = null;
        if($model->load(Yii::$app->request->post())){
            if($model->validate()){
                $table = new Alumnos;
                $table->tipo_documento = strtoupper($model->tipo_documento);
                $table->numero_documento = $model->numero_documento;
                $table->primer_nombre = strtoupper($model->primer_nombre);
                $table->segundo_nombre = strtoupper($model->segundo_nombre);
                $table->primer_apellido = strtoupper($model->primer_apellido);
                $table->segundo_apellido = strtoupper($model->segundo_apellido);
                $table->grado = $model->grado;
                $table->telefono = $model->telefono;
                $table->celular = $model->celular;
                $table->direccion = strtoupper($model->direccion);
                $table->id_jornada = $model->jornada;
                $table->id_ciudad = $model->ciudad;
                $table->codigo = $model->codigo;
                $table->tipo_documento_acudiente = $model->tipo_documento_acudiente;
                $table->documento_acudiente = $model->documento_acudiente;
                $table->primer_nombre_acudiente = $model->primer_nombre_acudiente;
                $table->segundo_nombre_acudiente = $model->segundo_nombre_acudiente;
                $table->primer_apellido_acudiente = $model->primer_apellido_acudiente;
                $table->segundo_apellido_acudiente = $model->segundo_apellido_acudiente;
                $table->parentesco_acudiente = $model->parentesco;
                $table->telefono_acudiente = $model->telefono_acudiente;
                $table->celular_acudiente = $model->celular_acudiente;
                $table->direccion_acudiente = $model->direccion_acudiente;
                if($table->insert()){
                    $msg= "Alumno Creado Exitosamente";
                    $model->tipo_documento = null;
                    $model->numero_documento = null;
                    $model->primer_nombre = null;
                    $model->segundo_nombre = null;
                    $model->primer_apellido = null;
                    $model->segundo_apellido = null;
                    $model->grado = null;
                    $model->telefono = null;
                    $model->celular = null;
                    $model->direccion = null;
                    $model->jornada = null;
                    $model->ciudad = null;
                    $model->codigo = null;
                    $model->tipo_documento_acudiente = null;
                    $model->documento_acudiente = null;
                    $model->primer_nombre_acudiente = null;
                    $model->segundo_nombre_acudiente = null;
                    $model->primer_apellido_acudiente = null;
                    $model->segundo_apellido_acudiente = null;
                    $model->parentesco = null;
                    $model->telefono_acudiente = null;
                    $model->celular_acudiente = null;
                    $model->direccion_acudiente = null;
                }else{
                    $msg = "Ha ocurrido un error al insertar el registro";
                }   
            }else{
                $model->getErrors();
            }
        }
        return $this->render("createalumno",['model'=>$model,'msg'=>$msg]);
    }
    public function actionCreateprofesor(){
        return $this->render("createprofesor");
    }
    public function actionSaludo($get="Tutorial Yii"){
        $mensaje = "Hola mundo Yii2";
        $numeros = [0,1,2,3,4];
        return $this->render("saludo",["mensaje"=>$mensaje,"datos"=>$numeros,"get"=>$get]);
    }
    public function actionForma($mensaje=null){
        return $this->render("forma",["mensaje"=>$mensaje]);
    }
    public function actionRequest(){
        $mensaje = "";
        if(isset($_REQUEST["nombre"])){
            $mensaje = "El nombre enviado es ".strtoupper($_REQUEST['nombre']);
        }
        $this->redirect(["site/forma","mensaje"=>$mensaje]);
    }
    public function actionValidaforma(){
        $model = new ValidaForma;
        if($model->load(Yii::$app->request->post())){
            if($model->validate()){
                //por ejemplo consultar en una base de datos
            }else{
                $model->getErrors();
            }
        }
        return $this->render("validaforma",["model"=>$model]);
    }
    public function actionValidaformaajax(){
        $model = new ValidaFormaAjax;
        $msg   = null;
        if($model->load(Yii::$app->request->post()) && Yii::$app->request->isAjax){
            Yii::$app->response->format = Response::FORMAT_JSON;
            return ActiveForm::validate($model);
        }
        if($model->load(Yii::$app->request->post())){
            if($model->validate()){
                //hacer consulta a base de datoa
                $msg = "Datos enviados correctamente";
                $model->nombre = null;

views/site/about.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;

$this->title = 'About';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-about">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        This is the About page. You may modify the following file to customize its content:
    </p>

    <code><?= __FILE__ ?></code>
</div>

views/site/acceso.php
<?php
/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\LoginForm */
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use app\models\Perfiles;
use yii\helpers\ArrayHelper;

$this->title = 'Login';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-login">
    <div class="col-lg-offset-1" style="color:#999;">
        <p>Bienvenido al módulo de colegios, por favor seleccione su perfil e ingrese su cédula
        si es la primer vez que ingresa el sistema<br>le pedirá que genere un password, de lo contrario lo llevará
        al formulario de Login.</p>
    </div>
    <?php $form = ActiveForm::begin([
        'id' => 'login-form',
        'layout' => 'horizontal',
        'fieldConfig' => [
            'template' => "{label}\n<div class=\"col-lg-3\">{input}</div>\n<div class=\"col-lg-8\">{error}</div>",
            'labelOptions' => ['class' => 'col-lg-1 control-label'],
        ],
    ]); 
    ?>
    <div class="row">
        <?= $form->field($model, 'perfil')->dropDownList(ArrayHelper::map(Perfiles::find()->all(), 'id_perfil', 'nombre_perfil'),["prompt"=>"Seleccionar..."],['autofocus' => true]) ?>
        <?= $form->field($model, 'username')->textInput() ?>
    </div>
    <div class="form-group">
        <div class="col-lg-offset-1 col-lg-11">
            <?= Html::submitButton('Login', ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>
        </div>
    </div>
    <?php ActiveForm::end(); ?>
</div>

views/site/contact.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\ContactForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\captcha\Captcha;

$this->title = 'Contact';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-contact">
    <h1><?= Html::encode($this->title) ?></h1>

    <?php if (Yii::$app->session->hasFlash('contactFormSubmitted')): ?>

        <div class="alert alert-success">
            Thank you for contacting us. We will respond to you as soon as possible.
        </div>

        <p>
            Note that if you turn on the Yii debugger, you should be able
            to view the mail message on the mail panel of the debugger.
            <?php if (Yii::$app->mailer->useFileTransport): ?>
                Because the application is in development mode, the email is not sent but saved as
                a file under <code><?= Yii::getAlias(Yii::$app->mailer->fileTransportPath) ?></code>.
                Please configure the <code>useFileTransport</code> property of the <code>mail</code>
                application component to be false to enable email sending.
            <?php endif; ?>
        </p>

    <?php else: ?>

        <p>
            If you have business inquiries or other questions, please fill out the following form to contact us.
            Thank you.
        </p>

        <div class="row">
            <div class="col-lg-5">

                <?php $form = ActiveForm::begin(['id' => 'contact-form']); ?>

                    <?= $form->field($model, 'name')->textInput(['autofocus' => true]) ?>

                    <?= $form->field($model, 'email') ?>

                    <?= $form->field($model, 'subject') ?>

                    <?= $form->field($model, 'body')->textarea(['rows' => 6]) ?>

                    <?= $form->field($model, 'verifyCode')->widget(Captcha::className(), [
                        'template' => '<div class="row"><div class="col-lg-3">{image}</div><div class="col-lg-6">{input}</div></div>',
                    ]) ?>

                    <div class="form-group">
                        <?= Html::submitButton('Submit', ['class' => 'btn btn-primary', 'name' => 'contact-button']) ?>
                    </div>

                <?php ActiveForm::end(); ?>

            </div>
        </div>

    <?php endif; ?>
</div>

views/site/createalumno.php
<?php
use yii\helpers\Html;
use yii\helpers\ArrayHelper;
use yii\widgets\ActiveForm;
use yii\helpers\Url;
use app\models\Grados;
use app\models\Ciudades;
use app\models\TipoDocumento;
use app\models\Parentesco;

$this->title = 'Crear Alumnos';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="col-md-12 order-md-1">
    <h2 class="mb-3">CREACIÓN DE ALUMNOS</h2>
    <a href="<?= Url::toRoute("site/viewalumno")?>" class="btn btn-success">Ver Alumnos</a>
    <div class="alert alert-success"><?= $msg ?></div>
    <?php $form = ActiveForm::begin([
        "method" => "post",
        'enableClientValidation' => true,
    ]);
    ?>
    <div class="row"><h3><b>Informacion Personal</b></h3></div>
    <div class="row">
         <div class="col-md-3 mb-3">
            <?= $form->field($model, 'tipo_documento')->dropDownList(ArrayHelper::map(TipoDocumento::find()->all(), 'id_tipo', 'tipo'),["prompt"=>"Seleccionar..."]) ?>
        </div>
        <div class="col-md-9 mb-3">
            <?= $form->field($model, "numero_documento")->input("text") ?>   
        </div>       
    </div>
    <div class="row">
        <div class="col-md-3 mb-3">
            <?= $form->field($model, "primer_nombre")->input("text") ?>
        </div>
        <div class="col-md-3 mb-3">
            <?= $form->field($model, "segundo_nombre")->input("text") ?>   
        </div>   
        <div class="col-md-3 mb-3">
            <?= $form->field($model, "primer_apellido")->input("text") ?>
        </div>
        <div class="col-md-3 mb-3">
            <?= $form->field($model, "segundo_apellido")->input("text") ?>   
        </div>
    </div>
    <div class="row"> 
        <div class="col-md-3 mb-3">
            <?= $form->field($model, 'grado')->dropDownList(ArrayHelper::map(Grados::find()->all(), 'id_grado', 'grado'),["prompt"=>"Seleccionar..."]) ?>
        </div>
        <div class="col-md-3 mb-3">
            <?= $form->field($model, "telefono")->input("text") ?>
        </div>
        <div class="col-md-3 mb-3">
            <?= $form->field($model, "celular")->input("text") ?>   
        </div>
        <div class="col-md-3 mb-3">
            <?= $form->field($model, 'ciudad')->dropDownList(ArrayHelper::map(Ciudades::find()->all(), 'codigo', 'nombre_ciudad'),["prompt"=>"Seleccionar..."]) ?>
        </div>
    </div>
    <div class="row">
        <div class="col-md-6 mb-3">
            <?= $form->field($model, "direccion")->input("text") ?>
        </div>
        <div class="col-md-3 mb-3">
            <?= $form->field($model, "codigo")->input("text") ?>
        </div>
        <div class="col-md-3 mb-3">
            <?= $form->field($model, "jornada")->input("text") ?>   
        </div>
    </div>
    <div class="row"><h3><b>Informacion Del Acudiente</b></h3></div>
    <div class="row">
         <div class="col-md-3 mb-3">
            <?= $form->field($model, 'parentesco')->dropDownList(ArrayHelper::map(Parentesco::find()->all(), 'id_parentesco', 'parentesco'),["prompt"=>"Seleccionar..."]) ?>
        </div>        
         <div class="col-md-3 mb-3">
            <?= $form->field($model, 'tipo_documento_acudiente')->dropDownList(ArrayHelper::map(TipoDocumento::find()->all(), 'id_tipo', 'tipo'),["prompt"=>"Seleccionar..."]) ?>
        </div>
        <div class="col-md-6 mb-3">
            <?= $form->field($model, "documento_acudiente")->input("text") ?>   
        </div>       
    </div>
    <div class="row">
        <div class="col-md-3 mb-3">
            <?= $form->field($model, "primer_nombre_acudiente")->input("text") ?>
        </div>
        <div class="col-md-3 mb-3">
            <?= $form->field($model, "segundo_nombre_acudiente")->input("text") ?>   
        </div>   
        <div class="col-md-3 mb-3">
            <?= $form->field($model, "primer_apellido_acudiente")->input("text") ?>
        </div>
        <div class="col-md-3 mb-3">
            <?= $form->field($model, "segundo_apellido_acudiente")->input("text") ?>   
        </div>
    </div>
    <div class="row">
        <div class="col-md-3 mb-3">
            <?= $form->field($model, "telefono_acudiente")->input("text") ?>
        </div>
        <div class="col-md-3 mb-3">
            <?= $form->field($model, "celular_acudiente")->input("text") ?>
        </div>
        <div class="col-md-6 mb-3">
            <?= $form->field($model, "direccion_acudiente")->input("text") ?>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12 mb-3">
            <?= Html::submitButton("Crear Alumno", ["class" => "btn btn-primary"]) ?>
        </div>
    </div>
    <?php $form->end() ?>
</div>

views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

views/site/forma.php
<div class="alert alert-info"><h3>ESTE ES MI PRIMER FORMULARIO EN YII2</h3></div>
<h5 class="alert alert-success"><b><?= $mensaje ?></b></h5>
<?php
use yii\helpers\Url;
use yii\helpers\Html;

echo Html::beginForm(
        Url::toRoute("site/request"),//action
        "get",
        ["class"=>"form-inline"]//options
);
?>
<div class="form-group">
    <?= Html::label("Introduce tu nombre","nombre")?>
    <?= Html::textInput("nombre",null,["class"=>"form-control text-uppercase"]) ?>
</div>
<?= Html::submitInput("Enviar Nombre",["class"=>"btn btn-primary"]) ?>
<?= Html::endForm(); ?>

views/site/index.php
<?php

/* @var $this yii\web\View */
use yii\helpers\Url;
$this->title = '<span class="glyphicon glyphicon-globe"></span><strong>BIENVENIDOS A WE - COLEGIOS!</strong>';
?>
<div class="page-content">
    <div class="row">
        <div class="col-xs-6">
            <img src="<?php echo Yii::$app->request->baseUrl; ?>/images/WE.jpg" class="img-fluid img-thumbnail">
        </div>
        <div class="col-xs-6">     
            <h3>Bienvenido a We-Colegios</h3><br>
                <p class="text-justify">En esta comunidad puedes establecer comunicación entre los padres, alumnos y profesores en tiempo real y de manera fácil y segura
            </p>
        </div>
    </div>
</div>

views/site/login.php
<?php
/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\LoginForm */
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use app\models\Perfiles;
use yii\helpers\ArrayHelper;
$this->title = 'Login';
$this->params['breadcrumbs'][] = $this->title;
$username = @$_REQUEST['username'];
$perfil   = @$_REQUEST['perfil'];
?>
<div class="site-login">
    <p>Por favor diligencie los siguientes campos para loguearse:</p>
    <?php $form = ActiveForm::begin([
        'id' => 'login-form',
        'layout' => 'horizontal',
        'fieldConfig' => [
            'template' => "{label}\n<div class=\"col-lg-3\">{input}</div>\n<div class=\"col-lg-8\">{error}</div>",
            'labelOptions' => ['class' => 'col-lg-1 control-label'],
        ],
    ]); 
    ?>
    <?= $form->field($model, 'perfil')->dropDownList(ArrayHelper::map(Perfiles::find()->all(), 'id_perfil', 'nombre_perfil'),["prompt"=>"Seleccionar...","value"=>$perfil]) ?>
    <?= $form->field($model, 'username')->textInput(['value'=>$username]) ?>
    <?php
    if(isset($username)){
        $focus = true;
    }else{
        $focus = false;
    }
    ?>
    <?= $form->field($model, 'password')->passwordInput(['autofocus'=>$focus]) ?>
    <div class="form-group">
        <div class="col-lg-offset-1 col-lg-11">
            <?= Html::submitButton('Login', ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>
        </div>
    </div>
    <?php ActiveForm::end(); ?>
</div>

views/site/panel.php
<?php
use yii\helpers\Html;
use yii\helpers\ArrayHelper;
use yii\widgets\ActiveForm;
use yii\helpers\Url;
/* @var $this yii\web\View */
/* @var $dataProvider yii\data\ActiveDataProvider */
$this->title = 'Mi Panel';
$this->params['breadcrumbs'][] = $this->title;
?>
<!--Panel-->
<div class="card w-50">
    <div class="card-body">
        <h3 class="card-title">Bienvenido: <?= strtoupper($nombre) ?></h3>
        <p class="card-text"><b>Tus Opciones:</b></p>
        <a href="#" class="btn btn-primary">Ver Mensajes</a>
        <a href="<?= Url::toRoute("profesor/mensajeria")?>" class="btn btn-primary">Enviar Mensajes</a>
    </div>
</div>

views/site/saludo.php
<?php

/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

echo "<div class='alert alert-success'>".$mensaje."</div>";
for($a=0;$a<count($datos);$a++){
    echo "<b>".$datos[$a]."</b><br>";
}
echo "<h1 class='alert alert-info'>".strtoupper($get)."</h1>";

views/site/setpassword.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\LoginForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use app\models\SetearPassword;
use yii\helpers\ArrayHelper;
$this->title = 'Asignar Password';
$this->params['breadcrumbs'][] = $this->title;
$userid = $_REQUEST['userid'];
?>
<div class="site-login">
    <h1><?= Html::encode($this->title) ?></h1>
    <?php
        if(isset($msg)&& strlen($msg)>0){
            ?>
            <div class="alert alert-danger">Error al setear el password por favor intente nuevamente</div>
            <?php
        }
    ?>
    <div class="alert alert-info"><b>Por favor cree su password:</b></div>
    <?php $form = ActiveForm::begin(); 
    ?>
        <?= $form->field($modelpass, 'userid')->hiddenInput(['value'=>$userid])->label(false) ?>
        <?= $form->field($modelpass, 'password')->passwordInput() ?>
        <?= $form->field($modelpass, 'passrepeat')->passwordInput() ?>
    <div class="form-group">
        <?= Html::submitButton("Enviar",["class"=>"btn btn-primary"]);?>
    </div>    
    <?php $form->end() ?>
</div>

views/site/validaforma.php
<?php
use yii\helpers\Html;
use yii\widgets\ActiveForm;
?>
<h1>FORMULARIO VALIDADO</h1>

<?php

$form = ActiveForm::begin([
   "method"=>"post",
   "enableClientValidation"=>true
]);
?>
<div class="form-group">
    <?= $form->field($model, "nombre")->input("text"); ?>
</div>
<div class="form-group">
    <?= $form->field($model, "email")->input("email"); ?>
</div>
<?= Html::submitButton("Enviar",["class"=>"btn btn-primary"]);?>
<?php

$form->end();

?>


views/site/validaformaajax.php
<?php
use yii\helpers\Html;
use yii\widgets\ActiveForm;
?>
<h1>FORMULARIO VALIDADO CON AJAX</h1>
<div class="alert-success"><?= $msg?></div>
<?php

$form = ActiveForm::begin([
   "method"=>"post",
   "id"=>"formulario",
   "enableClientValidation"=>false,
   "enableAjaxValidation"=>true
]);
?>
<div class="form-group">
    <?= $form->field($model, "nombre")->input("text"); ?>
</div>
<div class="form-group">
    <?= $form->field($model, "email")->input("email"); ?>
</div>
<?= Html::submitButton("Enviar",["class"=>"btn btn-primary"]);?>
<?php

$form->end();

?>

views/site/viewalumno.php
<?php
use yii\helpers\Url;
use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\data\Pagination;
use yii\widgets\LinkPager;
?>
<a href="<?= Url::toRoute("site/createalumno")?>" class="btn btn-success">Crear Alumnos</a>

<?php $f = ActiveForm::begin([
    "method" => "get",
    "action"=> Url::toRoute("site/viewalumno"),
    "enableClientValidation"=>true,
]);
?>
<div class="form form-group">
    <?= $f->field($form,"q")->input("search") ?>
</div>
<?= Html::submitButton("Buscar",["class"=>"btn btn-primary"])?>
<?php $f->end() ?>
<h3><?= $search ?></h3>
<h3>Lista de Alumnos</h3>

<table class="table table-bordered">
    <tr>
        <td>Tipo Documento</td>
        <td>Id. Alumno</td>
        <td>Nombre</td>
        <td>Grado</td>
        <td>Codigo</td>
        <td>Telefono</td>
        <td>Celular</td>
        <td></td>
    </tr>
    <?php
    foreach ($model as $val){
        ?>
        <tr>
            <td><?= $val->tipo_documento?></td>
            <td><?= $val->numero_documento?></td>
            <td><?= strtoupper($val->primer_nombre." ".$val->segundo_nombre." ".$val->primer_apellido." ".$val->segundo_apellido)?></td>
            <td><?= $val->grado ?></td>
            <td><?= $val->codigo?></td>
            <td><?= $val->telefono?></td>
            <td><?= $val->celular?></td>
            <td>
                <a hef="<?= Url::toRoute(["site/updatealumno","id_alumno"=>$val->id_alumno])?>"><span class="glyphicon glyphicon-pencil"></span></a>
                <a hef="#" data-toggle="modal" data-target="#id_alumno_<?= $val->id_alumno?>"><span class="glyphicon glyphicon-trash"></span></a>
                <div class="modal fade" tabindex="-1" role="dialog" id="id_alumno_<?= $val->id_alumno?>">
                  <div class="modal-dialog" role="document">
                    <div class="modal-content">
                      <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                        <h4 class="modal-title">Eliminar Alumnos</h4>
                      </div>
                      <div class="modal-body">
                        <p>Realmente deseas eliinar el alumno?</p>
                      </div>
                      <div class="modal-footer">
                          <?= Html::beginForm(Url::toRoute("site/deletealumno"),"POST"); ?>
                          <input type="hidden" name="id_alumno" value="<?= $val->id_alumno ?>">
                            <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
                            <button type="submit" class="btn btn-primary">Aceptar</button>
                          <?php Html::endForm(); ?>  
                      </div>
                    </div><!-- /.modal-content -->
                  </div><!-- /.modal-dialog -->
                </div><!-- /.modal -->                
            </td>
        </tr>    
        <?php
    }
    ?>
</table>
<center>
<?= 
    LinkPager::widget([
        "pagination"=>$pages
    ]);    
?>
</center>